### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by patrolli** [hbdat/iccv21_relational_direction#4]
Hello! I was running the hico dataset and following the data preparation instruction. But the code cannot run and it reports missing the `/data/hico_20160224_det/json/hoi_list.json` file. I cannot find this file from the oringinal tar.gz file of hico dataset. Looking forward for your help, thx.

**Comment by patrolli** [comment]
I find how to extract these json files, from: https://github.com/BigRedT/no_frills_hoi_det

**Comment by zzzhhh1031** [comment]
> 我找到如何从中提取这些json文件：https://github.com/BigRedT/no_frills_hoi_det

Hello, I also encountered the same problem, how to get this file ？
